--
-- PostgreSQL database dump
--

-- Dumped from database version 14.18 (Debian 14.18-1.pgdg120+1)
-- Dumped by pg_dump version 14.18 (Debian 14.18-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: clientes; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.clientes (
    cliente_id bigint NOT NULL,
    direccion character varying(255),
    edad integer NOT NULL,
    genero character varying(255) NOT NULL,
    identificacion character varying(255) NOT NULL,
    nombre character varying(255) NOT NULL,
    telefono character varying(255),
    contrasena character varying(255) NOT NULL,
    estado boolean NOT NULL
);


ALTER TABLE public.clientes OWNER TO "user";

--
-- Name: clientes_cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.clientes ALTER COLUMN cliente_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cuentas; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.cuentas (
    id bigint NOT NULL,
    cliente_id bigint NOT NULL,
    estado character varying(255) NOT NULL,
    numero_cuenta character varying(255) NOT NULL,
    saldo_inicial double precision NOT NULL,
    tipo_cuenta character varying(255) NOT NULL
);


ALTER TABLE public.cuentas OWNER TO "user";

--
-- Name: cuentas_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.cuentas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuentas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movimientos; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.movimientos (
    id bigint NOT NULL,
    fecha date NOT NULL,
    saldo double precision NOT NULL,
    tipo_movimiento character varying(255) NOT NULL,
    valor double precision NOT NULL,
    cuenta_id bigint NOT NULL
);


ALTER TABLE public.movimientos OWNER TO "user";

--
-- Name: movimientos_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.movimientos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimientos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: clientes; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.clientes (cliente_id, direccion, edad, genero, identificacion, nombre, telefono, contrasena, estado) FROM stdin;
1	Otavalo sn y principal 	30	Masculino	9999999999	Jose Lema	098254785 	1234	t
2	Amazonas y NNUU 	30	Femenimo	1999999999	Marianela Montalvo	097548965 	5678	t
3	13 junio y Equinoccial 	30	Masculino	2999999999	Juan Osorio 	098874587 	1245	t
\.


--
-- Data for Name: cuentas; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.cuentas (id, cliente_id, estado, numero_cuenta, saldo_inicial, tipo_cuenta) FROM stdin;
1	1	true	478758	2000	Ahorros
5	1	true	585545	1000	Corriente
2	2	true	225487	700	Corriente
3	3	true	495878	150	Ahorros
4	2	true	496825	0	Ahorros
\.


--
-- Data for Name: movimientos; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.movimientos (id, fecha, saldo, tipo_movimiento, valor, cuenta_id) FROM stdin;
1	2025-05-15	700	DEPOSITO	600	2
2	2025-05-15	150	DEPOSITO	150	3
3	2025-05-15	0	RETIRO	540	4
\.


--
-- Name: clientes_cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.clientes_cliente_id_seq', 3, true);


--
-- Name: cuentas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.cuentas_id_seq', 5, true);


--
-- Name: movimientos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.movimientos_id_seq', 3, true);


--
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (cliente_id);


--
-- Name: cuentas cuentas_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.cuentas
    ADD CONSTRAINT cuentas_pkey PRIMARY KEY (id);


--
-- Name: movimientos movimientos_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT movimientos_pkey PRIMARY KEY (id);


--
-- Name: cuentas uk7h7mqvcau3mcl0mbrkdrt7fnh; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.cuentas
    ADD CONSTRAINT uk7h7mqvcau3mcl0mbrkdrt7fnh UNIQUE (numero_cuenta);


--
-- Name: clientes ukmvqpaay4xno9pnlalro0awadi; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT ukmvqpaay4xno9pnlalro0awadi UNIQUE (identificacion);


--
-- Name: movimientos fk4moe88hxuohcysas5h70mdc09; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT fk4moe88hxuohcysas5h70mdc09 FOREIGN KEY (cuenta_id) REFERENCES public.cuentas(id);


--
-- PostgreSQL database dump complete
--

